### ISSUE TITLE
Website - Summer Updates - Sticky Video Player

### ISSUE THREAD

**Issue by agBabbbyCakes** [ApeAcademy/ApeAcademy.github.io#2]
Website - Summer Updates - Sticky Video Player

Research
- https://discourse.webflow.com/t/sticky-youtube-video-on-scroll/115790

Feature 
- When a user scrolls down - and the video is playing - have the video stick to the bottom right of the page

**Comment by NotPeopling2day** [comment]
Closing https://linear.app/apeworx/issue/ACA-24/summer-updates-sticky-video-player
